//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckoutUser
    {
        public int CheckoutID { get; set; }
        public int UserID { get; set; }
    
        public virtual Checkout Checkout { get; set; }
    }
}
