//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckoutDetails
    {
        public int ID { get; set; }
        public int CheckoutID { get; set; }
        public string Title { get; set; }
        public decimal VND { get; set; }
        public Nullable<decimal> USD { get; set; }
        public Nullable<decimal> EUR { get; set; }
        public string DeptCode { get; set; }
        public string No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Checkout Checkout { get; set; }
    }
}
