//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetails
    {
        public int ID { get; set; }
        public int TicketID { get; set; }
        public string Title { get; set; }
        public int Quantity { get; set; }
        public string Reason { get; set; }
        public System.DateTime DateRequire { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
